### ISSUE TITLE
Periodically download data from BALTRAD server

### ISSUE THREAD

**Issue by peterdesmet** [enram/infrastructure#1]
### Do we really need to build this? And if so, how do we keep it simple?

Yes, we at least need access to the data to build anything at all.

### Questions

* [ ] How do we get access to the BALTRAD server? @leijnse can you email us the credentials?
* [ ] How is the BALTRAD server organized?
* [x] How often do we need to download the data? **A: Daily**

**Comment by adokter** [comment]
Most likely OPERA will request that data are made available with a delay of two days, to prevent any real-time operations. I therefore think downloading data once a day is sufficient.

**Comment by peterdesmet** [comment]
@adokter we would like to start setting up a file repository, while @bartaelterman is still working with us. Are there any hdf5 files on BALTRED already that we can test this on?

**Comment by adokter** [comment]
@peterdesmet @bartaelterman Here is a [file repo](https://github.com/adokter/vol2bird/tree/develop/h5-repo/vp) of vertical profiles of birds, as generated with the latest version of `vol2bird`. Not all polar volume files on which these profiles were calculated contained the necessary data (see [README](https://github.com/adokter/vol2bird/tree/develop/h5-repo)), so you will find some of the profiles do not contain any data.

Note also the [issue](https://github.com/adokter/vol2bird/issues/45) that nodetects (in case where radar didn't survey the airspace) and nodatas (when radar did survey the airspace, but quantity could not be determined) are currently both encoded as 'NaN' - that will change in the near future.

**Comment by peterdesmet** [comment]
Great, so that is something we could currently use as the "source" repo for these kind of data, later to be replaced by the BALTRAD server?

**Comment by adokter** [comment]
Yes, the baltrad server will generate identical files, only the directory structure remains to be decided. I will be visiting SMHI mid July to set up a prototype data flow.

**Comment by adokter** [comment]
@peterdesmet @bartaelterman The directory with test files is now in its [own repository](https://github.com/adokter/ODIM-hdf5-test), so no longer a folder in the develop branch of [vol2bird](https://github.com/adokter/vol2bird/tree/develop/)

**Comment by peterdesmet** [comment]
Thanks, good to know!

**Comment by peterdesmet** [comment]
@adokter 

* On the data repository, should we store/backup `vp` data or `pvol` data as well?
* What is the relation between these types of data?
* Is one derived from the other?
* Can one NOT be made public as open data?
* Do you expect other types of source data?

**Comment by bartaelterman** [comment]
[Here](https://github.com/enram/infrastructure/tree/download_service/download_service) is code that will assist with downloading files from a Github repo. Execute [this example script](https://github.com/enram/infrastructure/blob/download_service/example.py) to download all `hdf5` files from @adokter 's repo (selecting only files from the `vp` dir).

@peterdesmet @stijnvanhoey thoughts on the setup?

**Comment by peterdesmet** [comment]
Code to connect to source data (on GitHub) is now at https://github.com/enram/infrastructure/blob/master/data_repository/connectors.py. Data will be downloaded daily from BALTRAD once in production.
