### ISSUE TITLE
Develop local to S3 script

### ISSUE THREAD

**Issue by peterdesmet** [enram/infrastructure#20]
Requirements are the same as https://github.com/enram/infrastructure/blob/master/file_transfer/README.md#baltrad-to-s3, but rather than getting the files from the Baltrad server, they are uploaded from a local folder.

Alternatively, we can require that the files should be on "a" FTP server, but that seems like an odd requirement.

**Comment by stijnvanhoey** [comment]
fixed

**Comment by peterdesmet** [comment]
Maybe worthwile to document the features of this and the Baltrad to S3 script at https://github.com/enram/infrastructure/tree/master/file_transfer. I'll make a separate issue.
