### ISSUE TITLE
Decide on directory structure and filenames in S3

### ISSUE THREAD

**Issue by peterdesmet** [enram/infrastructure#21]
The directory structure was originally defined here: https://github.com/enram/infrastructure/issues/2#issuecomment-218742098 as 

    radar/yyyy/mm/dd/hh/radar_yyyymmddhhmm.h5

The [current proposal](https://github.com/enram/infrastructure/tree/master/file_transfer#baltrad-to-s3) is:

    country/radar/yyyy/mm/dd/hh/countryradar_vp_yyyymmddhhmmss.h5 (e.g. dkrom_vp_20170114231500.h5)

1. The country was added because 1) it is part of the file name and 2) it is probably a more convenient first level for navigation.
2. The `_vp_` was added because it is part of the file name on the Baltrad FTP and we didn't want to unnecessarily change the file name
3. The same apply for the seconds in the file name.

**Comment by adokter** [comment]
I like this directory structure
