### ISSUE TITLE
Extract and store radar metadata

### ISSUE THREAD

**Issue by peterdesmet** [enram/infrastructure#4]
### Do we really need to build this? And if so, how do we keep it simple?

For the flow visualization, we at least need some information on the location of the radars. Maybe a static file with all available radars and their coordinates and name suffices? Alternatively (more complicated), we could extract metadata from the HDF5 files and build an automatically updated metadata file.

**A: Load it from the metadata + all metadata should be time based (as radars can move)**

**Comment by peterdesmet** [comment]
I have moved the settings requirement to issue #7

**Comment by adokter** [comment]
The radar location (lat, lon) and official identifier used by WMO (world meteorological organisation) is stored in the metadata, and I prefer to load it from there into a database table containing radar properties, radar settings, and algorithm settings

**Comment by adokter** [comment]
[hdfview](https://www.hdfgroup.org/products/java/hdfview/) is a reasonably handy tool to quickly inspect hdf5 files and its contained data and metadata

**Comment by peterdesmet** [comment]
Decided to store metadata in DB. Still need to figure out how to translate this to a data model, but that's another issue.
