### ISSUE TITLE
Offer a webservice for radar metadata & settings

### ISSUE THREAD

**Issue by peterdesmet** [enram/infrastructure#8]
### Do we really need to build this? And if so, how do we keep it simple?

We only need this for 1) visualizations and 2) a web app to browse the data availability (#12). If we use a static file (see #4), we could just copy the file in those applications to have the necessary data. The usefulness of a webservice largely depends on the nature of the data: if static, it is less useful. If dynamic (e.g. because we include settings, see #7) it becomes more useful.

**Comment by adokter** [comment]
Nice to have, but currently not the core bottleneck. I see a relational database that can be queried  currently as the minimum requirement. Also, we can only proceed with open access bird products with permission from OPERA, which is pending

**Comment by peterdesmet** [comment]
Will indeed be stored in DB and can thus be queried. We'll only provide derived products if there are apps/viz who need those.
